name: jest

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '11.12.x'
    - name: yarn install
      run: yarn install
    - name: Run jest test
      run: yarn test