name: Go

on: [push]

jobs:
  testGo:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Build
        run: go build -v ./... 
        working-directory: ./api
      - name: Test
        run: go test -v ./...
        working-directory: ./api
